GET http://localhost:3001/persons/

###

DELETE http://localhost:3001/persons/63e671a0fce1a4aec39832da

###

POST http://localhost:3001/persons/ 
Content-Type: application/json

{
"name": "titit", "number": "58"
}